export default {
  ADMIN: 'ADMIN',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  HOSPITAL_MANAGER: 'HOSPITAL_MANAGER',
  RECEPTIONIST: 'RECEPTIONIST',
  DOCTOR: 'DOCTOR',
  PATIENT: 'PATIENT',
  AUTHENTICATED: 'AUTHENTICATED',
};
